[package]
name = "dioxus_android_app"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7", default-features = false, features = ["mobile", "launch", "lib"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
